# Generated by Django 6.0 on 2025-12-29 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='تاريخ الحصة')),
                ('is_present', models.BooleanField(default=True, verbose_name='حضور؟')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='ملاحظة سلوكية')),
                ('homework_score', models.IntegerField(blank=True, null=True, verbose_name='درجة الواجب')),
                ('homework_max', models.IntegerField(default=10, verbose_name='درجة الواجب النهائية')),
                ('class_exam_score', models.IntegerField(blank=True, null=True, verbose_name='درجة امتحان الحصة')),
                ('class_exam_max', models.IntegerField(default=10, verbose_name='درجة امتحان الحصة النهائية')),
                ('recitation_score', models.IntegerField(blank=True, null=True, verbose_name='درجة التسميع')),
                ('recitation_max', models.IntegerField(default=10, verbose_name='درجة التسميع النهائية')),
                ('comprehensive_exam_score', models.IntegerField(blank=True, null=True, verbose_name='درجة الامتحان الشامل')),
                ('comprehensive_exam_max', models.IntegerField(default=50, verbose_name='درجة الشامل النهائية')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_logs', to='teachers.group')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_logs', to='accounts.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='تم قبول الطلب')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='teachers.group')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='accounts.studentprofile')),
            ],
            options={
                'unique_together': {('student', 'group')},
            },
        ),
    ]
