# Generated by Django 6.0 on 2025-12-31 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='performancelog',
            name='session_number',
            field=models.PositiveIntegerField(default=1, verbose_name='رقم الحصة'),
        ),
    ]
