# Generated by Django 6.0 on 2026-01-03 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_performancelog_session_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='مقبول'),
        ),
        migrations.AlterField(
            model_name='performancelog',
            name='class_exam_max',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='performancelog',
            name='class_exam_score',
            field=models.IntegerField(blank=True, null=True, verbose_name='امتحان الحصة'),
        ),
        migrations.AlterField(
            model_name='performancelog',
            name='comprehensive_exam_max',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='performancelog',
            name='comprehensive_exam_score',
            field=models.IntegerField(blank=True, null=True, verbose_name='الشامل'),
        ),
        migrations.AlterField(
            model_name='performancelog',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='performancelog',
            name='homework_max',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='performancelog',
            name='homework_score',
            field=models.IntegerField(blank=True, null=True, verbose_name='الواجب'),
        ),
        migrations.AlterField(
            model_name='performancelog',
            name='is_present',
            field=models.BooleanField(default=True, verbose_name='حضور'),
        ),
        migrations.AlterField(
            model_name='performancelog',
            name='note',
            field=models.CharField(blank=True, max_length=200, verbose_name='ملاحظات'),
        ),
        migrations.AlterField(
            model_name='performancelog',
            name='recitation_max',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='performancelog',
            name='recitation_score',
            field=models.IntegerField(blank=True, null=True, verbose_name='التسميع'),
        ),
    ]
