# Generated by Django 6.0 on 2026-01-06 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_enrollment_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_paid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='VideoViewTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='عدد مرات المشاهدة')),
                ('is_completed', models.BooleanField(default=False, verbose_name='تمت المشاهدة (أخذ الدرجة)')),
                ('points_awarded', models.PositiveIntegerField(default=0, verbose_name='النقاط المكتسبة')),
            ],
        ),
    ]
