# Generated by Django 6.0 on 2026-01-06 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_studentprofile_enrolled_centers_and_more'),
        ('students', '0004_packageenrollment_videoviewtracking'),
        ('teachers', '0007_coursepackage'),
    ]

    operations = [
        migrations.AddField(
            model_name='packageenrollment',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='teachers.coursepackage'),
        ),
        migrations.AddField(
            model_name='packageenrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_enrollments', to='accounts.studentprofile'),
        ),
        migrations.AddField(
            model_name='videoviewtracking',
            name='lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.lecture'),
        ),
        migrations.AddField(
            model_name='videoviewtracking',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.coursepackage'),
        ),
        migrations.AddField(
            model_name='videoviewtracking',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.studentprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='packageenrollment',
            unique_together={('student', 'package')},
        ),
        migrations.AlterUniqueTogether(
            name='videoviewtracking',
            unique_together={('student', 'package', 'lecture')},
        ),
    ]
