# Generated by Django 6.0 on 2026-01-06 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_studentprofile_enrolled_centers_and_more'),
        ('exams', '0003_question_image'),
        ('students', '0005_packageenrollment_package_packageenrollment_student_and_more'),
        ('teachers', '0009_coursepackage_grade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.exam')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.coursepackage')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.studentprofile')),
            ],
            options={
                'unique_together': {('student', 'package', 'exam')},
            },
        ),
    ]
