# Generated by Django 6.0 on 2026-07-15 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_studentprofile_enrolled_centers_and_more'),
        ('students', '0006_packageexamresult'),
        ('teachers', '0015_subscriptionplan_is_default'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['student', 'is_active'], name='enrollment_student_active_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['group', 'is_active'], name='enrollment_group_active_idx'),
        ),
    ]
