services:
  - type: web
    name: ta3alm-academy  # اسم موقعك
    runtime: python
    plan: free # الخطة المجانية
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn ta3alm_project.wsgi:application # استبدل ta3alm_project باسم مجلد إعداداتك
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0