# Generated by Django 6.0.6 on 2026-07-18 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_subject'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='المبلغ')),
                ('payment_type', models.CharField(choices=[('teacher_subscription', 'اشتراك معلم'), ('student_package', 'شراء حزمة طالب')], max_length=50, verbose_name='نوع العملية')),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('approved', 'مقبول'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='الحالة')),
                ('target_id', models.PositiveIntegerField(blank=True, help_text='ID الباقة أو الحزمة', null=True)),
                ('phone_number', models.CharField(max_length=50, verbose_name='رقم المحفظة / انستا باي')),
                ('receipt_image', models.ImageField(upload_to='receipts/', verbose_name='صورة الإيصال (سكرين شوت)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الطلب')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
        ),
    ]
