# Generated by Django 6.0.6 on 2026-07-26 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_manualpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='اسم الوحدة / المحور')),
                ('grade', models.CharField(choices=[('1_prep', 'أولى إعدادي'), ('2_prep', 'ثانية إعدادي'), ('3_prep', 'ثالثة إعدادي'), ('1_sec', 'أولى ثانوي'), ('2_sec', 'ثانية ثانوي'), ('3_sec', 'ثالثة ثانوي')], max_length=20, verbose_name='الصف الدراسي')),
                ('term', models.CharField(choices=[('1', 'الترم الأول'), ('2', 'الترم الثاني')], max_length=1, verbose_name='الترم')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='الترتيب')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='core.subject', verbose_name='المادة')),
            ],
            options={
                'verbose_name': 'وحدة دراسية',
                'verbose_name_plural': 'الوحدات الدراسية',
                'ordering': ['grade', 'subject', 'term', 'order'],
            },
        ),
        migrations.CreateModel(
            name='CurriculumLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='اسم الدرس')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='الترتيب')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='core.curriculumunit', verbose_name='الوحدة')),
            ],
            options={
                'verbose_name': 'درس',
                'verbose_name_plural': 'الدروس',
                'ordering': ['unit', 'order'],
            },
        ),
    ]
