# Generated by Django 6.0.6 on 2026-08-14 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_curriculumunit_curriculumlesson'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'المادة', 'verbose_name_plural': 'المواد الدراسية'},
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='is_ai_enabled',
            field=models.BooleanField(default=True, verbose_name='تفعيل ميزات الذكاء الاصطناعي'),
        ),
        migrations.AlterField(
            model_name='curriculumunit',
            name='grade',
            field=models.CharField(choices=[('1_primary', 'أولى ابتدائي'), ('2_primary', 'ثانية ابتدائي'), ('3_primary', 'ثالثة ابتدائي'), ('4_primary', 'رابعة ابتدائي'), ('5_primary', 'خامسة ابتدائي'), ('6_primary', 'سادسة ابتدائي'), ('1_prep', 'أولى إعدادي'), ('2_prep', 'ثانية إعدادي'), ('3_prep', 'ثالثة إعدادي'), ('1_sec', 'أولى ثانوي'), ('2_sec', 'ثانية ثانوي'), ('3_sec', 'ثالثة ثانوي')], max_length=20, verbose_name='الصف الدراسي'),
        ),
    ]
