# Generated by Django 6.0 on 2025-12-29 22:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15, verbose_name='رقم الهاتف')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AssistantJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='تم القبول')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('can_manage_students', models.BooleanField(default=True, verbose_name='إدارة الطلاب')),
                ('can_manage_exams', models.BooleanField(default=False, verbose_name='إدارة الامتحانات')),
                ('can_manage_videos', models.BooleanField(default=False, verbose_name='إدارة الفيديوهات')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistants_jobs', to='teachers.teacherprofile')),
                ('assistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='assistants.assistantprofile')),
            ],
            options={
                'unique_together': {('assistant', 'teacher')},
            },
        ),
    ]
