# Generated by Django 6.0 on 2026-01-03 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistantjob',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='مقبول'),
        ),
    ]
