# Generated by Django 6.0 on 2026-01-07 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0002_alter_assistantjob_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistantjob',
            name='can_manage_packages',
            field=models.BooleanField(default=False, verbose_name='إدارة الحزم'),
        ),
    ]
