# Generated by Django 6.0 on 2025-12-29 22:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('centers', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='enrolled_centers',
            field=models.ManyToManyField(blank=True, to='centers.centerprofile', verbose_name='السناتر المشترك معها'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='enrolled_teachers',
            field=models.ManyToManyField(blank=True, related_name='students', to='teachers.teacherprofile'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
