# Generated by Django 6.0 on 2026-01-03 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('teachers', '0003_alter_group_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='enrolled_centers',
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='enrolled_teachers',
            field=models.ManyToManyField(blank=True, related_name='students', to='teachers.teacherprofile', verbose_name='المدرسين المشترك معهم'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='parent_phone',
            field=models.CharField(max_length=15, verbose_name='رقم ولي الأمر'),
        ),
        migrations.AlterField(
            model_name='user',
            name='custom_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='كود المستخدم'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_banned',
            field=models.BooleanField(default=False, verbose_name='محظور'),
        ),
        migrations.AlterField(
            model_name='user',
            name='national_id',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='الرقم القومي'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'طالب'), ('teacher', 'معلم'), ('center', 'سنتر'), ('assistant', 'مساعد'), ('admin', 'مسؤول منصة')], default='student', max_length=20, verbose_name='نوع المستخدم'),
        ),
    ]
