# Generated by Django 6.0 on 2025-12-29 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الامتحان')),
                ('description', models.TextField(blank=True, verbose_name='وصف او تعليمات')),
                ('duration_minutes', models.PositiveIntegerField(default=30, verbose_name='مدة الامتحان بالدقائق')),
                ('is_active', models.BooleanField(default=False, verbose_name='تفعيل الامتحان؟')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='teachers.group')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='نص السؤال')),
                ('option_a', models.CharField(max_length=200, verbose_name='(A) الاختيار الأول')),
                ('option_b', models.CharField(max_length=200, verbose_name='(B) الاختيار الثاني')),
                ('option_c', models.CharField(max_length=200, verbose_name='(C) الاختيار الثالث')),
                ('option_d', models.CharField(max_length=200, verbose_name='(D) الاختيار الرابع')),
                ('correct_answer', models.CharField(choices=[('A', 'الاختيار الأول'), ('B', 'الاختيار الثاني'), ('C', 'الاختيار الثالث'), ('D', 'الاختيار الرابع')], max_length=1, verbose_name='الإجابة الصحيحة')),
                ('marks', models.PositiveIntegerField(default=1, verbose_name='درجة السؤال')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exams.exam')),
            ],
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(verbose_name='درجة الطالب')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='exams.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='accounts.studentprofile')),
            ],
            options={
                'unique_together': {('student', 'exam')},
            },
        ),
    ]
