# Generated by Django 6.0 on 2026-01-06 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_alter_exam_description_alter_exam_duration_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='questions/', verbose_name='صورة توضيحية'),
        ),
    ]
