# Generated by Django 6.0 on 2026-01-07 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_question_image'),
        ('teachers', '0011_alter_lecture_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='teachers.group'),
        ),
    ]
