# Generated by Django 6.0 on 2026-07-15 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_studentprofile_enrolled_centers_and_more'),
        ('exams', '0004_alter_exam_group'),
        ('teachers', '0015_subscriptionplan_is_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='option_a',
            field=models.CharField(max_length=200, verbose_name='اختيار A'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_b',
            field=models.CharField(max_length=200, verbose_name='اختيار B'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_c',
            field=models.CharField(max_length=200, verbose_name='اختيار C'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_d',
            field=models.CharField(max_length=200, verbose_name='اختيار D'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['group', 'is_active'], name='exam_group_active_idx'),
        ),
        migrations.AddIndex(
            model_name='examresult',
            index=models.Index(fields=['student', 'exam'], name='examresult_student_exam_idx'),
        ),
    ]
