# Generated by Django 6.0.6 on 2026-07-26 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_curriculumunit_curriculumlesson'),
        ('exams', '0005_alter_question_option_a_alter_question_option_b_and_more'),
        ('teachers', '0016_subscriptionplan_ai_exams_limit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='نص السؤال')),
                ('option_a', models.CharField(max_length=200, verbose_name='اختيار A')),
                ('option_b', models.CharField(max_length=200, verbose_name='اختيار B')),
                ('option_c', models.CharField(max_length=200, verbose_name='اختيار C')),
                ('option_d', models.CharField(max_length=200, verbose_name='اختيار D')),
                ('correct_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, verbose_name='الإجابة الصحيحة')),
                ('difficulty', models.CharField(choices=[('easy', 'سهل'), ('medium', 'متوسط'), ('hard', 'صعب')], default='medium', max_length=10, verbose_name='مستوى الصعوبة')),
                ('grade', models.CharField(max_length=20, verbose_name='الصف الدراسي')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teachers.teacherprofile', verbose_name='تم الإنشاء بواسطة')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_questions', to='core.curriculumlesson', verbose_name='الدرس')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_questions', to='core.subject', verbose_name='المادة')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_questions', to='core.curriculumunit', verbose_name='الوحدة')),
            ],
            options={
                'verbose_name': 'سؤال في البنك',
                'verbose_name_plural': 'بنك الأسئلة',
                'ordering': ['-created_at'],
            },
        ),
    ]
