# Generated by Django 6.0 on 2025-12-29 22:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المجموعة')),
                ('grade', models.CharField(choices=[('1_sec', 'الصف الأول الثانوي'), ('2_sec', 'الصف الثاني الثانوي'), ('3_sec', 'الصف الثالث الثانوي')], max_length=20, verbose_name='الصف الدراسي')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الباقة')),
                ('price', models.PositiveIntegerField(verbose_name='السعر (EGP)')),
                ('student_limit', models.PositiveIntegerField(verbose_name='حد الطلاب الأقصى')),
                ('description', models.TextField(blank=True, verbose_name='وصف الباقة')),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان المحاضرة')),
                ('video_link', models.URLField(verbose_name='رابط الفيديو (Youtube)')),
                ('description', models.TextField(blank=True, verbose_name='وصف المحاضرة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='teachers.group')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, verbose_name='نبذة عن المعلم')),
                ('subject', models.CharField(blank=True, max_length=100, verbose_name='المادة الدراسية')),
                ('fawry_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='كود الدفع فوري')),
                ('image', models.ImageField(blank=True, null=True, upload_to='teachers/', verbose_name='صورة المعلم')),
                ('subscription_end_date', models.DateTimeField(blank=True, null=True)),
                ('is_trial_used', models.BooleanField(default=False)),
                ('current_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teachers.subscriptionplan', verbose_name='الباقة الحالية')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teacherprofile')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='teachers.teacherprofile'),
        ),
        migrations.CreateModel(
            name='VideoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='كود المشاهدة')),
                ('is_used', models.BooleanField(default=False, verbose_name='هل تم استخدامه؟')),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='teachers.lecture')),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_codes', to='accounts.studentprofile')),
            ],
        ),
    ]
