# Generated by Django 6.0 on 2025-12-31 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='مفعلة (ظاهرة)'),
        ),
    ]
