# Generated by Django 6.0 on 2026-01-02 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_lecture_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='grade',
            field=models.CharField(choices=[('1_sec', 'الصف الأول الاعدادي'), ('2_sec', 'الصف الثاني الاعدادي'), ('3_sec', 'الصف الثالث الاعدادي'), ('1_sec', 'الصف الأول الثانوي'), ('2_sec', 'الصف الثاني الثانوي'), ('3_sec', 'الصف الثالث الثانوي')], max_length=20, verbose_name='الصف الدراسي'),
        ),
    ]
