# Generated by Django 6.0 on 2026-01-03 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_studentprofile_enrolled_centers_and_more'),
        ('teachers', '0003_alter_group_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherprofile',
            name='fawry_code',
        ),
        migrations.AlterField(
            model_name='group',
            name='grade',
            field=models.CharField(choices=[('1_p', 'الصف الأول الاعدادي'), ('2p', 'الصف الثاني الاعدادي'), ('3p', 'الصف الثالث الاعدادي'), ('1_sec', 'الصف الأول الثانوي'), ('2_sec', 'الصف الثاني الثانوي'), ('3_sec', 'الصف الثالث الثانوي')], max_length=20, verbose_name='الصف الدراسي'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='description',
            field=models.TextField(blank=True, verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='مفعلة'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='title',
            field=models.CharField(max_length=200, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='video_link',
            field=models.URLField(verbose_name='رابط الفيديو'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='amount',
            field=models.PositiveIntegerField(verbose_name='المبلغ'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='التاريخ'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='is_trial_used',
            field=models.BooleanField(default=False, verbose_name='هل استهلك الشهر المجاني؟'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='subscription_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ انتهاء الاشتراك'),
        ),
        migrations.AlterField(
            model_name='videocode',
            name='code',
            field=models.CharField(max_length=10, unique=True, verbose_name='الكود'),
        ),
        migrations.AlterField(
            model_name='videocode',
            name='is_used',
            field=models.BooleanField(default=False, verbose_name='مستخدم'),
        ),
        migrations.AlterField(
            model_name='videocode',
            name='used_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.studentprofile'),
        ),
    ]
