# Generated by Django 6.0 on 2026-01-06 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_remove_teacherprofile_fawry_code_alter_group_grade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocode',
            name='max_views',
            field=models.PositiveIntegerField(default=1, verbose_name='الحد الأقصى للمشاهدات'),
        ),
    ]
