# Generated by Django 6.0 on 2026-01-06 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0005_videocode_max_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocode',
            name='current_views',
            field=models.PositiveIntegerField(default=0, verbose_name='المشاهدات الحالية'),
        ),
        migrations.AlterField(
            model_name='videocode',
            name='is_used',
            field=models.BooleanField(default=False, verbose_name='تم التفعيل'),
        ),
        migrations.AlterField(
            model_name='videocode',
            name='max_views',
            field=models.PositiveIntegerField(default=1, verbose_name='حد المشاهدات'),
        ),
    ]
