# Generated by Django 6.0 on 2026-01-06 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_question_image'),
        ('teachers', '0006_videocode_current_views_alter_videocode_is_used_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='اسم الحزمة')),
                ('description', models.TextField(verbose_name='وصف الحزمة')),
                ('price', models.PositiveIntegerField(verbose_name='سعر الحزمة (EGP)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='packages/', verbose_name='صورة الغلاف')),
                ('view_limit', models.PositiveIntegerField(default=3, verbose_name='عدد مرات مشاهدة كل فيديو')),
                ('is_active', models.BooleanField(default=True, verbose_name='متاحة للشراء')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exams', models.ManyToManyField(related_name='packages', to='exams.exam', verbose_name='الامتحانات المختارة')),
                ('lectures', models.ManyToManyField(related_name='packages', to='teachers.lecture', verbose_name='المحاضرات المختارة')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='teachers.teacherprofile')),
            ],
        ),
    ]
