# Generated by Django 6.0 on 2026-01-06 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0007_coursepackage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='grade',
            field=models.CharField(choices=[('1_prep', 'الصف الأول الإعدادي'), ('2_prep', 'الصف الثاني الإعدادي'), ('3_prep', 'الصف الثالث الإعدادي'), ('1_sec', 'الصف الأول الثانوي'), ('2_sec', 'الصف الثاني الثانوي'), ('3_sec', 'الصف الثالث الثانوي')], max_length=20, verbose_name='الصف الدراسي'),
        ),
    ]
