# Generated by Django 6.0 on 2026-01-06 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0008_alter_group_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursepackage',
            name='grade',
            field=models.CharField(choices=[('1_prep', 'الصف الأول الإعدادي'), ('2_prep', 'الصف الثاني الإعدادي'), ('3_prep', 'الصف الثالث الإعدادي'), ('1_sec', 'الصف الأول الثانوي'), ('2_sec', 'الصف الثاني الثانوي'), ('3_sec', 'الصف الثالث الثانوي')], default='3_sec', max_length=20, verbose_name='الصف الدراسي'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='allow_online_groups',
            field=models.BooleanField(default=True, verbose_name='دعم الأونلاين'),
        ),
        migrations.AlterField(
            model_name='coursepackage',
            name='view_limit',
            field=models.PositiveIntegerField(default=3, verbose_name='حد المشاهدة للفيديو'),
        ),
    ]
