# Generated by Django 6.0 on 2026-01-07 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0009_coursepackage_grade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='الرصيد الحالي')),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='إجمالي الأرباح')),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='teachers.teacherprofile')),
            ],
        ),
        migrations.CreateModel(
            name='WithdrawRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ المطلوب')),
                ('method', models.CharField(choices=[('vodafone', 'Vodafone Cash'), ('instapay', 'InstaPay'), ('bank', 'Bank Transfer')], max_length=20, verbose_name='طريقة السحب')),
                ('details', models.TextField(verbose_name='بيانات التحويل (رقم/حساب)')),
                ('is_paid', models.BooleanField(default=False, verbose_name='تم التحويل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='teachers.wallet')),
            ],
        ),
    ]
