# Generated by Django 6.0 on 2026-01-08 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0011_alter_lecture_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='allow_online_groups',
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='allow_online_packages',
            field=models.BooleanField(default=False, verbose_name='مسموح بالحزم الأونلاين'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='allow_question_images',
            field=models.BooleanField(default=False, verbose_name='مسموح بصور الأسئلة'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='assistant_limit',
            field=models.PositiveIntegerField(default=2, verbose_name='حد المساعدين'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='group_limit',
            field=models.PositiveIntegerField(default=5, verbose_name='حد المجموعات'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='student_limit',
            field=models.PositiveIntegerField(default=1000, verbose_name='حد الطلاب'),
        ),
    ]
