# Generated by Django 6.0 on 2026-01-08 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_subject'),
        ('teachers', '0012_remove_subscriptionplan_allow_online_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.subject', verbose_name='المادة'),
        ),
    ]
