# Generated by Django 6.0 on 2026-01-09 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0013_alter_teacherprofile_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الملف')),
                ('link', models.URLField(verbose_name='رابط الملف (Drive/Direct)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pdfs', to='teachers.group')),
            ],
        ),
        migrations.AddField(
            model_name='coursepackage',
            name='pdfs',
            field=models.ManyToManyField(blank=True, related_name='packages', to='teachers.pdffile', verbose_name='الملفات المختارة'),
        ),
    ]
