# Generated by Django 6.0 on 2026-01-09 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0014_pdffile_coursepackage_pdfs'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='باقة افتراضية (مجانية)'),
        ),
    ]
