# Generated by Django 6.0.6 on 2026-07-26 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0015_subscriptionplan_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='ai_exams_limit',
            field=models.PositiveIntegerField(default=0, verbose_name='حد توليد الامتحانات بالذكاء الاصطناعي (0 = غير مسموح)'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='ai_exams_used',
            field=models.PositiveIntegerField(default=0, verbose_name='الامتحانات المولدة هذا الشهر'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='ai_limit_reset_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
