# Generated by Django 6.0.6 on 2026-07-26 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0016_subscriptionplan_ai_exams_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='ai_daily_limit',
            field=models.PositiveIntegerField(default=1, verbose_name='الحد الأقصى اليومي لامتحانات AI'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='ai_limit_period',
            field=models.CharField(choices=[('daily', 'يومي'), ('weekly', 'أسبوعي'), ('monthly', 'شهري')], default='monthly', max_length=10, verbose_name='فترة التجديد لامتحانات AI'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='ai_daily_used',
            field=models.PositiveIntegerField(default=0, verbose_name='الامتحانات المولدة اليوم'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='ai_last_exam_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='ai_exams_limit',
            field=models.PositiveIntegerField(default=0, verbose_name='حد امتحانات AI خلال الفترة (0 = غير مسموح)'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='ai_exams_used',
            field=models.PositiveIntegerField(default=0, verbose_name='الامتحانات المولدة خلال الفترة'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='ai_limit_reset_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
