# Generated by Django 6.0 on 2026-07-15 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_role', models.CharField(choices=[('owner', 'مالك المنصة'), ('moderator', 'مشرف'), ('support', 'دعم فني'), ('finance', 'مسؤول مالي')], default='moderator', max_length=20, verbose_name='دور الإدارة')),
                ('is_active_admin', models.BooleanField(default=True, verbose_name='نشط')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('appointed_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التعيين')),
                ('appointed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointed_admins', to=settings.AUTH_USER_MODEL, verbose_name='عيَّنه')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'بروفايل مسؤول',
                'verbose_name_plural': 'بروفايلات المسؤولين',
                'ordering': ['admin_role', 'appointed_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('ban_user', 'حظر مستخدم'), ('unban_user', 'رفع حظر'), ('delete_user', 'حذف مستخدم'), ('renew_subscription', 'تجديد اشتراك'), ('edit_user', 'تعديل بيانات مستخدم'), ('add_plan', 'إضافة باقة'), ('edit_plan', 'تعديل باقة'), ('delete_plan', 'حذف باقة'), ('pay_withdrawal', 'تسديد طلب سحب'), ('toggle_maintenance', 'تغيير وضع الصيانة'), ('appoint_admin', 'تعيين مسؤول'), ('remove_admin', 'إزالة مسؤول')], max_length=50, verbose_name='الحدث')),
                ('target_label', models.CharField(blank=True, max_length=200, verbose_name='المستهدف (وصف)')),
                ('target_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID المستهدف')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='التفاصيل')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='وقت الحدث')),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='المسؤول المنفِّذ')),
            ],
            options={
                'verbose_name': 'سجل حدث',
                'verbose_name_plural': 'سجل الأحداث الإدارية',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['admin', 'created_at'], name='auditlog_admin_time_idx'), models.Index(fields=['action'], name='auditlog_action_idx')],
            },
        ),
    ]
