# Generated by Django 6.0.6 on 2026-09-08 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZohoMailConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(blank=True, help_text='معرف العميل من Zoho Developer Console', max_length=255, verbose_name='Client ID')),
                ('client_secret', models.CharField(blank=True, help_text='الرمز السري للعميل من Zoho Developer Console', max_length=255, verbose_name='Client Secret')),
                ('refresh_token', models.TextField(blank=True, help_text='توكن التجديد الدائم المستلم عبر OAuth 2.0', verbose_name='Refresh Token')),
                ('access_token', models.TextField(blank=True, help_text='التوكن المؤقت المستخدم حالياً في استدعاءات REST API', verbose_name='Access Token الحالي')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ انتهاء Access Token')),
                ('account_id', models.CharField(blank=True, help_text='معرف حساب البريد في Zoho (يتم جلبه تلقائياً)', max_length=100, verbose_name='Account ID')),
                ('support_email', models.EmailField(default='support@ta3alm.online', help_text='البريد المستخدم للإرسال والاستقبال', max_length=254, verbose_name='البريد المعتمد للدعم')),
                ('zoho_accounts_url', models.CharField(default='https://accounts.zoho.com', help_text='حسب نطاق السيرفر الجغرافي (مثل https://accounts.zoho.com أو .eu)', max_length=255, verbose_name='رابط المصادقة لـ Zoho Accounts')),
                ('zoho_api_url', models.CharField(default='https://mail.zoho.com/api', max_length=255, verbose_name='رابط الـ API الأساسي لـ Zoho Mail')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعل')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='آخر وقت مزامنة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'إعدادات Zoho Mail',
                'verbose_name_plural': 'إعدادات Zoho Mail',
            },
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('ban_user', 'حظر مستخدم'), ('unban_user', 'رفع حظر'), ('delete_user', 'حذف مستخدم'), ('renew_subscription', 'تجديد اشتراك'), ('edit_user', 'تعديل بيانات مستخدم'), ('add_plan', 'إضافة باقة'), ('edit_plan', 'تعديل باقة'), ('delete_plan', 'حذف باقة'), ('pay_withdrawal', 'تسديد طلب سحب'), ('toggle_maintenance', 'تغيير وضع الصيانة'), ('toggle_ai', 'تشغيل/إيقاف الذكاء الاصطناعي'), ('appoint_admin', 'تعيين مسؤول'), ('remove_admin', 'إزالة مسؤول'), ('zoho_reply', 'رد على بريد إلكتروني (Zoho)'), ('zoho_compose', 'إرسال بريد جديد (Zoho)')], max_length=50, verbose_name='الحدث'),
        ),
    ]
