from django.urls import path
from . import views

urlpatterns = [
    path('dashboard/', views.teacher_dashboard, name='teacher_dashboard'),
    path('paymob/checkout/', views.paymob_checkout, name='paymob_checkout'),
    path('paymob/callback/', views.payment_callback, name='payment_callback'),
    path('subscription/', views.subscription_info, name='subscription_info'),
    path('group/<int:group_id>/', views.group_detail, name='group_detail'),
    path('lecture/<int:lecture_id>/codes/', views.manage_video_codes, name='manage_video_codes'),
    path('group/<int:group_id>/students/', views.group_students, name='group_students'),
    path('group/<int:group_id>/', views.group_detail, name='group_detail'), 
    path('group/<int:group_id>/exams/', views.group_exams, name='group_exams'), 
    path('group/<int:group_id>/students/', views.group_students, name='group_students'),
    path('lecture/delete/<int:lecture_id>/', views.delete_lecture, name='delete_lecture'),
    path('settings/', views.teacher_settings, name='teacher_settings'),
    path('account/delete/', views.delete_teacher_account, name='delete_teacher_account'),
    path('group/edit/<int:group_id>/', views.edit_group, name='edit_group'),
    path('group/delete/<int:group_id>/', views.delete_group, name='delete_group'),    
    path('group/<int:group_id>/bulk-log/', views.bulk_log, name='bulk_log'),
    path('group/<int:group_id>/requests/', views.group_requests, name='group_requests'), 
    path('group/<int:group_id>/ranking/', views.group_ranking, name='group_ranking'),
    path('group/<int:group_id>/import/', views.import_group_content, name='import_group_content'),
    path('assistants/manage/', views.manage_assistants, name='manage_assistants'),
    path('group/<int:group_id>/student/<int:student_id>/log/', views.student_full_log, name='student_full_log'),
    path('lecture/toggle/<int:lecture_id>/', views.toggle_lecture_status, name='toggle_lecture_status'),
    path('packages/', views.teacher_packages, name='teacher_packages'),
    path('packages/', views.teacher_packages, name='teacher_packages'),
    path('packages/create/', views.create_package, name='create_package'),
    path('packages/<int:package_id>/edit/', views.edit_package, name='edit_package'),
    path('wallet/', views.teacher_wallet, name='teacher_wallet'),
    path('package/<int:package_id>/manage/', views.teacher_package_detail, name='teacher_package_detail'),
    path('package/<int:package_id>/students/', views.teacher_package_students, name='teacher_package_students'),
    path('package/<int:package_id>/ranking/', views.teacher_package_ranking, name='teacher_package_ranking'),
    path('package/<int:package_id>/import/', views.import_package_content, name='import_package_content'),
    path('package/<int:package_id>/remove-content/', views.remove_package_content, name='remove_package_content'),
    path('package/<int:package_id>/add-lecture/', views.add_lecture_to_package, name='add_lecture_to_package'),
    path('package/<int:package_id>/add-exam/', views.add_exam_to_package, name='add_exam_to_package'),
    path('group/<int:group_id>/add-pdf/', views.add_pdf_to_group, name='add_pdf_to_group'),
    path('package/<int:package_id>/add-pdf/', views.add_pdf_to_package, name='add_pdf_to_package'),
    path('pdf/delete/<int:pdf_id>/', views.delete_pdf, name='delete_pdf'),
    path('group/<int:group_id>/files/', views.group_files_teacher, name='group_files_teacher'),
    path('package/<int:package_id>/files/', views.package_files_teacher, name='package_files_teacher'),
    path('group/<int:group_id>/student/<int:student_id>/remove/', views.remove_student_from_group, name='remove_student_from_group'),
    path('api/teachers/', views.api_all_teachers),
    path('api/packages/', views.api_all_packages),
]
