# Generated by Django 6.0 on 2025-12-29 22:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CenterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center_name', models.CharField(max_length=150, verbose_name='اسم السنتر')),
                ('address', models.TextField(verbose_name='العنوان بالتفصيل')),
                ('contact_phone', models.CharField(max_length=15, verbose_name='رقم تواصل السنتر')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='center_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
