"""
Django settings for ta3alm_project project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-kimtwe+10w1p73-o5@o$+kg7mztvreg#_ey#@c9jd!eo%@wyh9'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['192.168.1.5', 'localhost', '127.0.0.1','inclined-chameleon-ta3alm-733d150d.koyeb.app']



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
        # Third party
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google', # لدخول جوجل

    # Local Apps
    'core',
    'accounts',
    'teachers',
    'students',
    'exams',
    'centers',
    'assistants',
]

AUTH_USER_MODEL = 'accounts.User'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # يجب أن يكون تحت Security مباشرة
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'ta3alm_project.middleware.BanMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'ta3alm_project.middleware.MaintenanceMiddleware',
]

AUTHENTICATION_BACKENDS = [
    # يسمح بتسجيل الدخول بالطريقة العادية (اسم مستخدم وباسورد)
    'django.contrib.auth.backends.ModelBackend',

    # يسمح بتسجيل الدخول عبر الايميل وجوجل (allauth)
    'allauth.account.auth_backends.AuthenticationBackend',
]


ROOT_URLCONF = 'ta3alm_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.notifications',
            ],
        },
    },
]

WSGI_APPLICATION = 'ta3alm_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'postgres',
        'USER': 'postgres.ubejysbctkxloejgjomp',  # اسم المستخدم من سوبابيز
        'PASSWORD': 'ta3alm.db.ENG.bod2', 
        'HOST': 'aws-1-eu-central-1.pooler.supabase.com',
        'PORT': '6543',
    }
}

# settings.py

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

from django.utils.translation import gettext_lazy as _
import os

# اللغة الافتراضية
LANGUAGE_CODE = 'ar'

# تفعيل الترجمة
USE_I18N = True
USE_L10N = True

# اللغات المدعومة
LANGUAGES = [
    ('ar', _('Arabic')),
    ('en', _('English')),
]

# مكان ملفات الترجمة
LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

TIME_ZONE = 'Africa/Cairo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
import os
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# ==========================================
# إعدادات AllAuth (Google Only Strict Mode)
# ==========================================
SITE_ID = 1
# بدلاً من الرئيسية، نوجهه لدالة الفرز
LOGIN_REDIRECT_URL = 'custom_login_redirect' 
LOGOUT_REDIRECT_URL = '/'

# 1. الاعتماد على الإيميل فقط
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False 
ACCOUNT_SIGNUP_PASSWORD_ENTER_TWICE = True # يطلب الباسورد مرتين # لا تطلب اسم مستخدم
# ACCOUNT_USER_MODEL_USERNAME_FIELD = None # إلغاء حقل اسم المستخدم من الفورم
ACCOUNT_EMAIL_VERIFICATION = 'none' # لا ترسل إيميل تفعيل
# السماح بتسجيل الخروج الفوري بمجرد الضغط على الرابط (بدون صفحة تأكيد)
ACCOUNT_LOGOUT_ON_GET = True

# 2. إعدادات السوشيال (الأهم)
SOCIALACCOUNT_AUTO_SIGNUP = True  # سجل فوراً دون فورم إضافي
SOCIALACCOUNT_EMAIL_VERIFICATION = 'none'
SOCIALACCOUNT_QUERY_EMAIL = True

# 3. إعدادات لجلب البيانات من جوجل
SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        },
        'EMAIL_AUTHENTICATION': True,
    }
}

#---------------------------------------------------------------
# إعدادات Paymob
PAYMOB_API_KEY = "ZXlKaGJHY2lPaUpJVXpVeE1pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SmpiR0Z6Y3lJNklrMWxjbU5vWVc1MElpd2ljSEp2Wm1sc1pWOXdheUk2TVRFeE9EWXdNQ3dpYm1GdFpTSTZJbWx1YVhScFlXd2lmUS5BX0o3bGZPa2wwdmJtU3VpcWZ1aEhNUHNiQ1A4blNEbzI3dFY4Mm5wVUhYTlhLSFZaZUJlNEw2eHpmQXB0SWJEdWstTHlISnNlVlYteXBTNDBwU0pBdw=="
PAYMOB_INTEGRATION_ID = 5450551  # استبدله برقم الـ Integration ID
PAYMOB_IFRAME_ID = 991968 

PAYMOB_WALLET_INTEGRATION_ID = 5462707     
# PAYMOB_WALLET_IFRAME_ID = 